/* hello-world.c generated by valac 0.40.24, the Vala compiler
 * generated from hello-world.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>




gint _vala_main (gchar** args,
                 int args_length1);


gint
_vala_main (gchar** args,
            int args_length1)
{
	gint result = 0;
	FILE* _tmp0_;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Hello World\n");
	result = 0;
	return result;
	result = 0;
	return result;
}


int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}



